### ISSUE TITLE
Video issue at 00:46:42, app dies after 46 minutes

### ISSUE THREAD

**Issue by PaulMcInnis** [uwaft/Data-Collection-App#8]
This is a very specific issue affecting recordings of a certain length

Something is causing the app to crash after 00:46:42 and around 4,106 megabytes of file size. Perhaps a FAT32 file size limitaiton? Might need to start and stop recording to avoid synchronization issues. 

Specific files to see example:
![image](https://cloud.githubusercontent.com/assets/3189865/24566695/79c251e6-1628-11e7-8506-71d5d73f82a8.png)

first step: see if the csv recorded the whole trip but the video recording just died.

**Comment by taipingli** [comment]
Is it possible for the J5 to have a exFAT formatted SD card? Otherwise, it does seem like you're not allowed to write more than 4GB to the file. Perhaps make it so that videos are broken up into segments, and then they can be stitched together on the Linux machine locally after upload. This way you also have smaller segments when recording, reducing the likelihood of data corruption. 

Looks like ffmpeg can do that (currently using it for removing audio), http://www.ffmpeg.org/faq.html#Concatenating-using-the-concat-demuxer

**Comment by PaulMcInnis** [comment]
using the info here: https://developer.android.com/reference/android/media/MediaRecorder.html
using the MEDIA_RECORDER_INFO_MAX_FILESIZE_REACHED check with a setOnInfoListener, 
I have set a 2 gig limit because that's the maximum that FAT filesystems can do (though FAT32 can do 4)

**Comment by PaulMcInnis** [comment]
closing this issue for now, though more seamless solutions using setNextOutputFile and MEDIA_RECORDER_INFO_NEXT_OUTPUT_FILE_STARTED and MEDIA_RECORDER_INFO_MAX_FILESIZE_APPROACHING  is possible
